timezone: Europe/Copenhagen
encoding: utf-8
baseurl: https://neurotechdk.github.io/
collections:
  resources:
    output: true
    permalink: /:collection/:path/
    sort:
      date: DESC
    relative_directory: resources
