timezone: Europe/Copenhagen
encoding: utf-8
baseurl: https://neurotechdk.github.io/
collections_dir: pages
collections:
  resource:
        output: true
defaults:
- scope:
    path: ""
    type: resource
  values:
    resource_type: "general"
    layout: default
- scope:
    path: "pages/_resource/document/"
    type: resource
  values:
    resource_type: "document"