title: NeurotechX Denmark
email: denmark@neurotechx.com
description: >- # this means to ignore newlines until "baseurl:"
  ...
baseurl: ""
url: "https://brainjammers.com/"
# twitter_username: jekyllrb
# github_username:  jekyll
timezone: Europe/Copenhagen
encoding: utf-8
social:
  twitter: https://twitter.com/NeuroTechDK
  facebook: https://www.facebook.com/groups/neurotechdk
  github: https://github.com/neurotechdk
collections_dir: pages
collections:
  resource:
        output: true
  event:
        output: true
  profile:
        output: true
defaults:
  -
    scope:
      path: "pages/_resource"
      type: "resource"
    values:
      resource_type: "general"
      layout: default
      permalink: /:collection/:path
  -
    scope:
      path: "pages/_resource/document"
      type: "resource"
    values:
      resource_type: "document"
  -
    scope:
      path: "pages/_resource/slide"
      type: "resource"
    values:
      resource_type: "slide"
  -
    scope:
      path: "pages/_event"
      type: "event"
    values:
      event_type: "brainjamm"
      event_start: 2018-01-01 09:00:00
      event_end: 2018-01-01 10:00:00
  -
    scope:
      path: "pages/_profile"
      type: "profile"
    values:
      profile_type: "about"
      layout: profile
      permalink: /about/:path
      profile_image: /assets/img/about/noprofile.png


