title: NeurotechX Denmark
email: denmark@neurotechx.com
description: >- # this means to ignore newlines until "baseurl:"
  ...
baseurl: ""
url: "https://brainjammers.com/"
# twitter_username: jekyllrb
# github_username:  jekyll
timezone: Europe/Copenhagen
encoding: utf-8
social:
  twitter: https://twitter.com/
  facebook: https://www.facebook.com/groups/neurotechdk
  github: https://github.com/neurotechdk
collections_dir: pages
collections:
  resource:
        output: true
defaults:
- scope:
    path: ""
    type: resource
  values:
    resource_type: "general"
    layout: default
- scope:
    path: "pages/_resource/document/"
    type: resource
  values:
    resource_type: "document"

