timezone: Europe/Copenhagen
encoding: utf-8
baseurl: https://neurotechdk.github.io/
collections_dir: sections
collections: ["resource"]
defaults:
- scope:
    path: ""
    type: resource
    output: true
  values:
    resource_type: "document"
    layout: default
